/**
 * Garden design commissions, pulled from willowalexandergardens.co.uk (the
 * studio's own "projects" post type: titles, slugs and full image galleries).
 * The source site carries no written descriptions, so copy is House-voice,
 * written to each project's real type. Images in
 * public/design/gardens/projects/<slug>/.
 */

export interface GardenProject {
  slug: string;
  title: string;
  location: string;
  type: string;
  summary: string;
  intro: string;
  images: string[];
}

export const GARDEN_PROJECTS: GardenProject[] = [
  {
    slug: "sevenoaks-outside-entertaining",
    title: "Outside Entertaining Garden",
    location: "Sevenoaks, Kent",
    type: "Entertaining garden",
    summary: "Mature trees, a striped lawn and deep borders built around long evenings outdoors.",
    intro: "This garden was designed around the table. Mature trees were kept and framed, a striped lawn gives the eye somewhere to rest, and deep borders draw you down to a terrace set for long summer evenings.\n\nLighting was planned from the start, so the garden carries on past dusk and reads as well from indoors in the dark as it does by day.",
    images: [
      "/design/gardens/projects/sevenoaks-outside-entertaining/01.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/02.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/03.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/04.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/05.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/06.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/07.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/08.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/09.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/10.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/11.webp",
      "/design/gardens/projects/sevenoaks-outside-entertaining/12.webp",
    ],
  },
  {
    slug: "beckenham-contemporary-english-garden",
    title: "Contemporary English Garden",
    location: "Beckenham, London",
    type: "Contemporary English",
    summary: "A crisp architectural frame softened by loose, naturalistic English planting.",
    intro: "A contemporary rear garden with the confidence of the house behind it. Clean lines, a generous terrace and a precise lawn give the structure; loose, naturalistic planting softens every edge.\n\nIt is contemporary English at heart: modern bones, romantic planting, a garden that holds its shape in winter and brims over in summer.",
    images: [
      "/design/gardens/projects/beckenham-contemporary-english-garden/01.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/03.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/10.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/11.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/12.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/02.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/04.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/05.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/06.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/07.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/08.webp",
      "/design/gardens/projects/beckenham-contemporary-english-garden/09.webp",
    ],
  },
  {
    slug: "contemporary-tiered-garden-design",
    title: "Contemporary English Tiered Garden",
    location: "Sevenoaks, Kent",
    type: "Contemporary English",
    summary: "A sloping plot resolved into broad, planted tiers, each one a room of its own.",
    intro: "A change in level became the making of this garden. Rather than fight the slope, we set it into broad tiers, each one a room in its own right, linked by stone and planting.\n\nThe scheme is contemporary English: structural evergreens threaded with grasses and perennials, so it reads beautifully from the house in every season.",
    images: [
      "/design/gardens/projects/contemporary-tiered-garden-design/01.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/02.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/03.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/04.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/05.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/06.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/07.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/08.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/09.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/10.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/11.webp",
      "/design/gardens/projects/contemporary-tiered-garden-design/12.webp",
    ],
  },
  {
    slug: "london-large-family-garden",
    title: "Large Family Garden",
    location: "London",
    type: "Family garden",
    summary: "A generous garden that works as hard for the children as for the planting.",
    intro: "A large garden asked to do several things at once: room to run, somewhere to sit, and borders worth looking at all year. We zoned it gently, a level lawn at the heart, stone steps linking the changes in level, deep planted borders holding it together.\n\nMaterials are honest and hard-wearing, chosen to weather well under real family use.",
    images: [
      "/design/gardens/projects/london-large-family-garden/01.webp",
      "/design/gardens/projects/london-large-family-garden/05.webp",
      "/design/gardens/projects/london-large-family-garden/06.webp",
      "/design/gardens/projects/london-large-family-garden/07.webp",
      "/design/gardens/projects/london-large-family-garden/09.webp",
      "/design/gardens/projects/london-large-family-garden/12.webp",
      "/design/gardens/projects/london-large-family-garden/02.webp",
      "/design/gardens/projects/london-large-family-garden/03.webp",
      "/design/gardens/projects/london-large-family-garden/04.webp",
      "/design/gardens/projects/london-large-family-garden/08.webp",
      "/design/gardens/projects/london-large-family-garden/10.webp",
    ],
  },
  {
    slug: "bromley-modern-cottage-garden",
    title: "Modern Cottage Garden",
    location: "Bromley, London",
    type: "Cottage garden",
    summary: "Cottage-garden romance on contemporary bones, generous but never unruly.",
    intro: "A modern take on the cottage garden: billowing, scented, generous planting set on clean contemporary structure. The romance is real, but it sits on firm bones, so the garden stays full without tipping into chaos.\n\nIt is planted for succession, with something coming into its own from the first bulbs to the last seed heads.",
    images: [
      "/design/gardens/projects/bromley-modern-cottage-garden/01.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/02.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/03.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/04.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/08.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/11.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/12.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/05.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/06.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/07.webp",
      "/design/gardens/projects/bromley-modern-cottage-garden/10.webp",
    ],
  },
  {
    slug: "sevenoaks-english-cottage-garden",
    title: "English Cottage Garden",
    location: "Sevenoaks, Kent",
    type: "Cottage garden",
    summary: "Billowing perennials and a pergola walk, structured enough to hold their shape.",
    intro: "A generous English cottage garden: billowing perennials, a pergola walk and paths that disappear into the planting. The structure is deliberate, clipped evergreens and a clear route, so the abundance never tips into mess.\n\nIt is planted for succession, in flower from the first bulbs of spring to the last seed heads of autumn.",
    images: [
      "/design/gardens/projects/sevenoaks-english-cottage-garden/01.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/02.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/03.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/04.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/05.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/06.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/07.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/08.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/09.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/10.webp",
      "/design/gardens/projects/sevenoaks-english-cottage-garden/11.webp",
    ],
  },
  {
    slug: "tropical-garden",
    title: "Tropical Garden",
    location: "London",
    type: "Tropical",
    summary: "Bold architectural foliage and lush layering for a sheltered city plot.",
    intro: "A sheltered London garden given over to drama: big architectural leaves, lush layering and a canopy that turns a small space into somewhere that feels a world away.\n\nThe planting is chosen for foliage first, so the garden stays exotic and full from late spring well into autumn.",
    images: [
      "/design/gardens/projects/tropical-garden/01.webp",
      "/design/gardens/projects/tropical-garden/02.webp",
      "/design/gardens/projects/tropical-garden/03.webp",
      "/design/gardens/projects/tropical-garden/04.webp",
      "/design/gardens/projects/tropical-garden/05.webp",
      "/design/gardens/projects/tropical-garden/06.webp",
      "/design/gardens/projects/tropical-garden/07.webp",
      "/design/gardens/projects/tropical-garden/08.webp",
      "/design/gardens/projects/tropical-garden/09.webp",
    ],
  },
  {
    slug: "balham-foliage-garden",
    title: "Foliage Garden",
    location: "Balham, London",
    type: "Foliage",
    summary: "A green-on-green garden carried by leaf shape and texture, not flower.",
    intro: "A garden that proves you do not need flowers to hold the eye. Here the interest is all in foliage, leaf shape, texture and shades of green layered against one another for a calm, architectural feel.\n\nIt stays full and considered for far longer than a flower-led scheme, and reads beautifully from the house all year.",
    images: [
      "/design/gardens/projects/balham-foliage-garden/01.webp",
      "/design/gardens/projects/balham-foliage-garden/02.webp",
      "/design/gardens/projects/balham-foliage-garden/03.webp",
      "/design/gardens/projects/balham-foliage-garden/04.webp",
      "/design/gardens/projects/balham-foliage-garden/05.webp",
      "/design/gardens/projects/balham-foliage-garden/06.webp",
      "/design/gardens/projects/balham-foliage-garden/07.webp",
      "/design/gardens/projects/balham-foliage-garden/08.webp",
      "/design/gardens/projects/balham-foliage-garden/09.webp",
      "/design/gardens/projects/balham-foliage-garden/10.webp",
      "/design/gardens/projects/balham-foliage-garden/11.webp",
    ],
  },
  {
    slug: "bermondsey-med-garden",
    title: "Mediterranean Garden",
    location: "Bermondsey, London",
    type: "Mediterranean",
    summary: "A sun-soaked Mediterranean courtyard of gravel, olives and aromatic planting.",
    intro: "A city courtyard reimagined as a slice of the Mediterranean: gravel underfoot, olives and architectural evergreens, aromatic planting that releases scent in the heat.\n\nDrought-tolerant and low-maintenance, it makes a sun-trap of a small urban space and asks very little in return.",
    images: [
      "/design/gardens/projects/bermondsey-med-garden/01.webp",
      "/design/gardens/projects/bermondsey-med-garden/02.webp",
      "/design/gardens/projects/bermondsey-med-garden/03.webp",
      "/design/gardens/projects/bermondsey-med-garden/04.webp",
      "/design/gardens/projects/bermondsey-med-garden/05.webp",
      "/design/gardens/projects/bermondsey-med-garden/06.webp",
      "/design/gardens/projects/bermondsey-med-garden/07.webp",
      "/design/gardens/projects/bermondsey-med-garden/08.webp",
      "/design/gardens/projects/bermondsey-med-garden/09.webp",
      "/design/gardens/projects/bermondsey-med-garden/10.webp",
      "/design/gardens/projects/bermondsey-med-garden/11.webp",
    ],
  },
  {
    slug: "chislehurst-sloped-garden",
    title: "Tiered Garden",
    location: "Chislehurst, London",
    type: "Tiered garden",
    summary: "A sloping garden terraced into usable, planted levels.",
    intro: "A sloping Chislehurst plot, terraced into a series of usable levels and held with clean retaining walls. Each tier earns its place, lawn, planting, somewhere to sit, linked by steps that make the climb feel designed.\n\nPlanting settles the new structure into the slope, so it reads as garden rather than engineering.",
    images: [
      "/design/gardens/projects/chislehurst-sloped-garden/01.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/02.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/03.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/04.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/05.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/06.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/07.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/08.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/09.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/10.webp",
      "/design/gardens/projects/chislehurst-sloped-garden/12.webp",
    ],
  },
  {
    slug: "wrotham-large-sloped-garden",
    title: "Large Sloped Garden",
    location: "Wrotham, Kent",
    type: "Sloped garden",
    summary: "A steep hillside plot terraced into a sequence of planted garden rooms.",
    intro: "A large, steeply sloping plot that was hard to use and harder to plant. We terraced it into a sequence of usable levels, held with raised beds and retaining walls, then planted boldly to settle the structure into the hillside.\n\nWhat was an awkward bank now reads as a series of garden rooms, each with its own outlook over the valley.",
    images: [
      "/design/gardens/projects/wrotham-large-sloped-garden/01.webp",
      "/design/gardens/projects/wrotham-large-sloped-garden/02.webp",
      "/design/gardens/projects/wrotham-large-sloped-garden/03.webp",
      "/design/gardens/projects/wrotham-large-sloped-garden/04.webp",
      "/design/gardens/projects/wrotham-large-sloped-garden/05.webp",
      "/design/gardens/projects/wrotham-large-sloped-garden/06.webp",
      "/design/gardens/projects/wrotham-large-sloped-garden/07.webp",
      "/design/gardens/projects/wrotham-large-sloped-garden/08.webp",
    ],
  },
  {
    slug: "woodland-garden",
    title: "Woodland Garden",
    location: "Sevenoaks, Kent",
    type: "Woodland",
    summary: "A shaded plot embraced as woodland, with dappled planting under mature trees.",
    intro: "Rather than fight the shade of mature trees, this garden leans into it. Woodland planting, ferns, shade-lovers and spring bulbs, settles naturally beneath the canopy, with a path that draws you through the dappled light.\n\nIt is a quiet, naturalistic garden that feels older than it is.",
    images: [
      "/design/gardens/projects/woodland-garden/01.webp",
      "/design/gardens/projects/woodland-garden/02.webp",
      "/design/gardens/projects/woodland-garden/08.webp",
      "/design/gardens/projects/woodland-garden/09.webp",
      "/design/gardens/projects/woodland-garden/10.webp",
      "/design/gardens/projects/woodland-garden/11.webp",
      "/design/gardens/projects/woodland-garden/12.webp",
      "/design/gardens/projects/woodland-garden/03.webp",
      "/design/gardens/projects/woodland-garden/04.webp",
      "/design/gardens/projects/woodland-garden/05.webp",
      "/design/gardens/projects/woodland-garden/06.webp",
    ],
  },
  {
    slug: "white-garden",
    title: "White Garden",
    location: "Orpington, London",
    type: "Planting scheme",
    summary: "A restrained white-and-green planting scheme that glows at dusk.",
    intro: "A garden held to a single palette: whites, creams and green, with the discipline that makes a white garden work. The restraint is the point, the planting reads as one calm, considered whole.\n\nIt comes into its own at dusk, when the white flowers hold the last of the light long after the rest of the garden has gone to shadow.",
    images: [
      "/design/gardens/projects/white-garden/01.webp",
      "/design/gardens/projects/white-garden/02.webp",
      "/design/gardens/projects/white-garden/03.webp",
      "/design/gardens/projects/white-garden/04.webp",
      "/design/gardens/projects/white-garden/05.webp",
      "/design/gardens/projects/white-garden/06.webp",
      "/design/gardens/projects/white-garden/08.webp",
      "/design/gardens/projects/white-garden/09.webp",
      "/design/gardens/projects/white-garden/07.webp",
    ],
  },
  {
    slug: "clapham-family-garden",
    title: "Family Garden",
    location: "Clapham, London",
    type: "Family garden",
    summary: "A compact town garden that feels larger than it is, calm and green-led.",
    intro: "A London family garden that needed to feel bigger than its boundaries. Curved borders draw the eye around rather than straight to the fence, a clean lawn keeps the centre open, and the planting stays green-led and calm.\n\nIt is built for real family use, hard-wearing underfoot and forgiving through the seasons.",
    images: [
      "/design/gardens/projects/clapham-family-garden/03.webp",
      "/design/gardens/projects/clapham-family-garden/04.webp",
      "/design/gardens/projects/clapham-family-garden/06.webp",
      "/design/gardens/projects/clapham-family-garden/08.webp",
      "/design/gardens/projects/clapham-family-garden/09.webp",
      "/design/gardens/projects/clapham-family-garden/10.webp",
      "/design/gardens/projects/clapham-family-garden/02.webp",
      "/design/gardens/projects/clapham-family-garden/05.webp",
      "/design/gardens/projects/clapham-family-garden/07.webp",
    ],
  },
  {
    slug: "kent-family-garden",
    title: "Family Garden",
    location: "Kent",
    type: "Family garden",
    summary: "A suburban plot reshaped by generous planting, drawn in for privacy by pleached hornbeam.",
    intro: "A typical suburban garden, transformed by adding ample planting throughout. Where the plot was open and overlooked, deep, generous borders now give it structure and a quiet sense of enclosure.\n\nTall pleached hornbeam trees add height and interest along the boundaries, hugging the garden in and lending privacy without closing it off. It is a garden made to feel held, settled into its surroundings rather than exposed by them.",
    images: [
      "/design/gardens/projects/kent-family-garden/04.webp",
      "/design/gardens/projects/kent-family-garden/02.webp",
      "/design/gardens/projects/kent-family-garden/03.webp",
      "/design/gardens/projects/kent-family-garden/05.webp",
      "/design/gardens/projects/kent-family-garden/06.webp",
    ],
  },
  {
    slug: "chelsfield-cottage-garden",
    title: "Cottage Garden",
    location: "Chelsfield, Kent",
    type: "Cottage garden",
    summary: "A classic English cottage garden, loose and full on quiet structure.",
    intro: "A classic cottage garden, loose and full, with self-seeders allowed their head among the borders. Underneath the romance sits quiet structure, clipped shapes and a clear path, that keeps the whole thing legible.\n\nPlanted for a long season of interest, it is a garden made to be wandered through rather than viewed from the house.",
    images: [
      "/design/gardens/projects/chelsfield-cottage-garden/01.webp",
      "/design/gardens/projects/chelsfield-cottage-garden/03.webp",
      "/design/gardens/projects/chelsfield-cottage-garden/04.webp",
      "/design/gardens/projects/chelsfield-cottage-garden/05.webp",
      "/design/gardens/projects/chelsfield-cottage-garden/06.webp",
      "/design/gardens/projects/chelsfield-cottage-garden/08.webp",
      "/design/gardens/projects/chelsfield-cottage-garden/09.webp",
      "/design/gardens/projects/chelsfield-cottage-garden/10.webp",
      "/design/gardens/projects/chelsfield-cottage-garden/02.webp",
      "/design/gardens/projects/chelsfield-cottage-garden/07.webp",
    ],
  },
  {
    slug: "tiered-front-garden",
    title: "Tiered Front Garden",
    location: "Chislehurst, London",
    type: "Front garden",
    summary: "A sloping front garden terraced into tidy, planted levels.",
    intro: "A sloping front garden, terraced into tidy planted levels that handle the change in height between street and door. Raised beds hold the structure; contemporary planting and grasses soften it.\n\nIt turns an awkward slope into a considered arrival, looked after with very little fuss.",
    images: [
      "/design/gardens/projects/tiered-front-garden/01.webp",
      "/design/gardens/projects/tiered-front-garden/02.webp",
      "/design/gardens/projects/tiered-front-garden/03.webp",
      "/design/gardens/projects/tiered-front-garden/04.webp",
      "/design/gardens/projects/tiered-front-garden/05.webp",
      "/design/gardens/projects/tiered-front-garden/06.webp",
      "/design/gardens/projects/tiered-front-garden/07.webp",
      "/design/gardens/projects/tiered-front-garden/08.webp",
      "/design/gardens/projects/tiered-front-garden/10.webp",
      "/design/gardens/projects/tiered-front-garden/11.webp",
      "/design/gardens/projects/tiered-front-garden/09.webp",
    ],
  },
  {
    slug: "formal-front-garden",
    title: "Formal Front Garden",
    location: "Bromley, London",
    type: "Front garden",
    summary: "A symmetrical, evergreen front garden that looks composed all year.",
    intro: "A formal front garden built on symmetry and evergreen structure: clipped shapes, a clear axis and a calm, composed face to the street.\n\nThe restraint is deliberate, it looks cared-for in every season and asks little to stay that way.",
    images: [
      "/design/gardens/projects/formal-front-garden/01.webp",
      "/design/gardens/projects/formal-front-garden/06.webp",
      "/design/gardens/projects/formal-front-garden/07.webp",
      "/design/gardens/projects/formal-front-garden/08.webp",
      "/design/gardens/projects/formal-front-garden/09.webp",
      "/design/gardens/projects/formal-front-garden/02.webp",
      "/design/gardens/projects/formal-front-garden/03.webp",
      "/design/gardens/projects/formal-front-garden/04.webp",
      "/design/gardens/projects/formal-front-garden/05.webp",
    ],
  },
  {
    slug: "front-garden",
    title: "Front Garden",
    location: "Sevenoaks, Kent",
    type: "Front garden",
    summary: "A welcoming front garden in soft grasses and perennials, parking kept quietly in hand.",
    intro: "A front garden sets the tone for the whole house, and has to earn its keep: arrival, parking, first impression. Here a gravel path threads through grasses and long-flowering perennials, so coming home feels like walking into a garden rather than onto a driveway.\n\nThe palette is soft and low-maintenance, chosen to look cared-for without asking much of a busy household.",
    images: [
      "/design/gardens/projects/front-garden/01.webp",
      "/design/gardens/projects/front-garden/02.webp",
      "/design/gardens/projects/front-garden/03.webp",
      "/design/gardens/projects/front-garden/04.webp",
      "/design/gardens/projects/front-garden/05.webp",
      "/design/gardens/projects/front-garden/06.webp",
      "/design/gardens/projects/front-garden/07.webp",
      "/design/gardens/projects/front-garden/08.webp",
      "/design/gardens/projects/front-garden/09.webp",
      "/design/gardens/projects/front-garden/10.webp",
      "/design/gardens/projects/front-garden/11.webp",
      "/design/gardens/projects/front-garden/12.webp",
    ],
  },
  {
    slug: "sevenoaks-gravel-garden",
    title: "Gravel Garden",
    location: "Sevenoaks, Kent",
    type: "Gravel garden",
    summary: "A relaxed, drought-tolerant gravel garden of grasses and self-seeders.",
    intro: "A gravel garden built for ease and movement: drought-tolerant planting threaded through gravel, grasses catching the wind, self-seeders softening the edges.\n\nIt asks little, no mowing, little watering, and gives a great deal, a loose naturalistic garden that looks good for most of the year.",
    images: [
      "/design/gardens/projects/sevenoaks-gravel-garden/01.webp",
      "/design/gardens/projects/sevenoaks-gravel-garden/02.webp",
      "/design/gardens/projects/sevenoaks-gravel-garden/03.webp",
      "/design/gardens/projects/sevenoaks-gravel-garden/04.webp",
      "/design/gardens/projects/sevenoaks-gravel-garden/05.webp",
    ],
  },
];

export const getGardenProject = (slug: string): GardenProject | undefined =>
  GARDEN_PROJECTS.find((p) => p.slug === slug);
