/**
 * A flat index of every insurance cover the House introduces, with search tags,
 * powering the "Find your cover" search on the insurance hub. Base tags below;
 * an exhaustive brand/breed/model/item keyword map (EXTRA) is merged in so the
 * specific things people type ("toyota", "labrador", "rolex", "worcester bosch",
 * "plumber", "loft conversion") resolve to the right cover. This module is
 * dynamically imported by CoverFinder, so it is NOT in the initial page bundle.
 */
export type CoverIndexEntry = {
  name: string;
  blurb: string;
  href: string;
  image: string;
  group: string;
  tags: string[];
};

const BASE_COVERS: CoverIndexEntry[] = [
  // Everyday
  { name: "Home insurance", blurb: "Buildings and contents for a standard home.", href: "/insurance/everyday/home", image: "/insurance/ev-home.webp", group: "Everyday cover", tags: ["home", "house", "buildings", "contents", "standard", "flat", "apartment", "household", "possessions", "accidental damage"] },
  { name: "Car, van & motorbike", blurb: "Including temporary cover from one hour to 28 days.", href: "/insurance/everyday/motor", image: "/insurance/ev-motor.webp", group: "Everyday cover", tags: ["car", "van", "motorbike", "motorcycle", "moped", "scooter", "vehicle", "temporary", "learner", "motor"] },
  { name: "Pet & travel", blurb: "Pet cover, and single-trip or annual travel.", href: "/insurance/everyday/pet-and-travel", image: "/insurance/ev-pet.webp", group: "Everyday cover", tags: ["pet", "dog", "cat", "vet", "travel", "holiday", "trip", "medical"] },
  { name: "Breakdown & bicycle", blurb: "Roadside and recovery, and cover for bikes.", href: "/insurance/everyday/breakdown-and-bicycle", image: "/insurance/ev-breakdown.webp", group: "Everyday cover", tags: ["breakdown", "recovery", "roadside", "bicycle", "bike", "cycle"] },

  // Home cover
  { name: "Boiler & heating cover", blurb: "When the heating stops.", href: "/insurance/boiler-cover", image: "/insurance/boiler-cover.webp", group: "Home cover", tags: ["boiler", "heating", "central heating", "radiator", "plumbing", "hot water"] },
  { name: "Appliance cover", blurb: "The machines a home runs on.", href: "/insurance/appliance-cover", image: "/insurance/appliance-cover.webp", group: "Home cover", tags: ["appliance", "kitchen", "white goods"] },

  // Advised
  { name: "Private client", blurb: "Advised cover for period & high-value homes.", href: "/insurance/private-client", image: "/insurance/cat-house.webp", group: "Advised", tags: ["advised", "private client", "estate", "luxury", "one policy", "renewal"] },

  // Specialist property
  { name: "Listed buildings", blurb: "Grade I, II* and II homes.", href: "/insurance/listed-buildings", image: "/insurance/listed.webp", group: "Specialist property", tags: ["listed", "grade", "heritage", "period", "conservation"] },
  { name: "Thatched properties", blurb: "Thatch, read on its real risk.", href: "/insurance/thatched-properties", image: "/insurance/thatched.webp", group: "Specialist property", tags: ["thatch", "thatched", "cottage"] },
  { name: "Non-standard construction", blurb: "Timber, cob, flint, steel and more.", href: "/insurance/non-standard-construction", image: "/insurance/non-standard.webp", group: "Specialist property", tags: ["non-standard", "non standard", "construction"] },
  { name: "Second & holiday homes", blurb: "Cover that fits real occupancy.", href: "/insurance/second-homes", image: "/insurance/holiday-home.webp", group: "Specialist property", tags: ["second home", "holiday home", "holiday let", "overseas"] },
  { name: "Unoccupied & probate", blurb: "Empty homes, calmly covered.", href: "/insurance/unoccupied-property", image: "/insurance/probate.webp", group: "Specialist property", tags: ["unoccupied", "empty", "probate"] },
  { name: "Renovation & works", blurb: "One policy for the works.", href: "/insurance/renovation-and-extension", image: "/insurance/renovation.webp", group: "Specialist property", tags: ["renovation", "extension", "works", "building"] },

  // Assets & advice
  { name: "Fine art, jewellery & collections", blurb: "Art, jewellery, watches and wine.", href: "/insurance/fine-art-and-collections", image: "/insurance/cat-fine-art.webp", group: "Assets & advice", tags: ["fine art", "art", "jewellery", "jewelry", "watch", "wine", "collection", "collections", "valuables"] },
  { name: "Classic & prestige motor", blurb: "The car, on one renewal date.", href: "/insurance/classic-and-prestige-motor", image: "/insurance/cat-cars.webp", group: "Assets & advice", tags: ["classic car", "classic", "prestige", "supercar", "agreed value"] },
  { name: "Boat, yacht & aviation", blurb: "Marine and aviation, on the estate.", href: "/insurance/boat-yacht-aviation", image: "/insurance/boat-yacht-aviation.webp", group: "Assets & advice", tags: ["boat", "yacht", "sailing", "sailboat", "motorboat", "narrowboat", "speedboat", "dinghy", "marine", "aviation", "aircraft", "aeroplane", "airplane", "plane", "helicopter", "private jet", "microlight", "mooring", "marina", "hangar", "lloyds", "lloyd's"] },
  { name: "Business insurance", blurb: "Introductions through the House's network.", href: "/insurance/business", image: "/insurance/cat-business.webp", group: "Assets & advice", tags: ["business", "commercial", "b2b", "company", "cyber"] },
  { name: "Trades & contractors", blurb: "Liability, tools and contract works.", href: "/insurance/business/trades-and-contractors", image: "/insurance/trades-hero.webp", group: "Assets & advice", tags: ["trades", "trade", "contractor", "liability", "tools"] },
  { name: "Professional indemnity", blurb: "Cover for advice given.", href: "/insurance/business/professional-indemnity", image: "/insurance/pi-hero.webp", group: "Assets & advice", tags: ["professional indemnity", "pi", "advice", "negligence"] },
];

/** Exhaustive brand / breed / model / item keywords, merged into the base tags. */
const EXTRA: Record<string, string[]> = {
  "/insurance/everyday/motor": ["toyota","ford","vauxhall","volkswagen","vw","bmw","mercedes","mercedes-benz","merc","audi","honda","nissan","kia","hyundai","peugeot","renault","citroen","ds","fiat","seat","cupra","skoda","volvo","mazda","mini","tesla","dacia","suzuki","mitsubishi","lexus","jeep","subaru","abarth","smart","chevrolet","chrysler","daewoo","daihatsu","isuzu","ssangyong","proton","saab","perodua","corsa","astra","insignia","fiesta","focus","kuga","mondeo","puma","golf","polo","passat","tiguan","t-roc","qashqai","juke","micra","leaf","yaris","corolla","aygo","rav4","c-hr","civic","jazz","cr-v","clio","captur","megane","scenic","kadjar","208","308","2008","3008","5008","c3","c1","c4","picanto","sportage","ceed","niro","i10","i20","tucson","ka","ibiza","leon","ateca","fabia","octavia","kamiq","panda","500","tipo","transit","transit custom","transit connect","sprinter","transporter","caddy","crafter","vivaro","trafic","master","movano","boxer","partner","berlingo","ducato","relay","combo","expert","dispatch","doblo","talento","nv200","nv400","primastar","interstar","luton","panel van","dropside","tipper","yamaha","kawasaki","ducati","triumph","harley","harley davidson","vespa","aprilia","ktm","royal enfield","moto guzzi","piaggio","lexmoto","sinnis","lambretta","gilera","cbr","r1","ninja","50cc","125cc","hatchback","saloon","estate","suv","crossover","mpv","people carrier","pickup","4x4","convertible","coupe","camper","campervan","motorhome","provisional","new driver","young driver","ev","electric","hybrid","plug-in","phev","diesel","petrol","dashcam","black box","telematics","multi car","multi-car"],
  "/insurance/classic-and-prestige-motor": ["ferrari","porsche","lamborghini","mclaren","aston martin","bentley","rolls royce","rolls-royce","maserati","jaguar","e-type","xk","xj","xjs","mk2","jensen","jensen interceptor","alfa romeo","alfa","lotus","esprit","elise","exige","evora","tvr","morgan","ac cobra","ac","austin healey","healey","mgb","mga","midget","tr6","tr4","spitfire","stag","range rover","defender","mustang","corvette","911","930","964","993","996","997","turbo","carrera","testarossa","daytona","dino","f40","f355","348","boxster","cayman","panamera","continental","phantom","corniche","silver shadow","silver spirit","quattroporte","ghibli","dbs","db5","db7","db9","db11","vantage","vanquish","spider","mini cooper","classic mini","morris","morris minor","clubman","escort","escort mexico","cortina","capri","anglia","rs2000","lotus cortina","gt40","beetle","split screen","karmann ghia","bug","2cv","datsun","240z","supra","skyline","gtr","gt-r","bugatti","koenigsegg","pagani","noble","ariel atom","caterham","westfield","hot rod","muscle car","american classic","vintage","veteran","pre-war","collector","collectable","guaranteed value","concours","track day","trackday","kit car","modern classic","restoration","project car","barn find","limited edition","hypercar","stored vehicle","laid up","multi vehicle","car collection"],
  "/insurance/everyday/pet-and-travel": ["labrador","labrador retriever","golden retriever","retriever","cocker spaniel","springer spaniel","working cocker","show cocker","spaniel","poodle","toy poodle","miniature poodle","cockapoo","cavapoo","labradoodle","goldendoodle","sprocker","french bulldog","frenchie","bulldog","english bulldog","american bulldog","dachshund","sausage dog","chihuahua","pug","beagle","boxer","border collie","collie","german shepherd","alsatian","husky","siberian husky","malamute","rottweiler","staffie","staffordshire bull terrier","staffordshire","american bully","jack russell","terrier","yorkshire terrier","yorkie","westie","border terrier","bull terrier","whippet","greyhound","lurcher","shih tzu","pomeranian","dalmatian","setter","pointer","weimaraner","vizsla","great dane","mastiff","bullmastiff","st bernard","newfoundland","bernese","doberman","dobermann","akita","shar pei","chow chow","basset hound","bloodhound","corgi","shiba inu","samoyed","schnauzer","miniature schnauzer","bichon frise","maltese","havanese","lhasa apso","papillon","cavalier","king charles spaniel","patterdale","cane corso","dogue de bordeaux","xl bully","persian","siamese","bengal","ragdoll","maine coon","british shorthair","british blue","sphynx","tabby","tortoiseshell","burmese","birman","russian blue","abyssinian","moggy","kitten","puppy","rabbit","bunny","guinea pig","crossbreed","mongrel","mixed breed","rescue dog","senior pet","multi pet","cruise","ski","snowboard","backpacking","gap year","single trip","annual multi-trip","annual multi trip","multi-trip","worldwide","europe","usa","baggage","cancellation","pre-existing","winter sports","business trip","city break","over 65","over 70","family holiday","gadget cover","missed departure"],
  "/insurance/boiler-cover": ["worcester bosch","worcester","bosch","vaillant","ideal","baxi","glow-worm","glow worm","viessmann","potterton","ferroli","main","alpha","ariston","vokera","biasi","intergas","heatline","keston","johnson starley","warmflow","grant","firebird","navien","combi","combi boiler","system boiler","conventional boiler","regular boiler","heat only","back boiler","gas boiler","gas","oil boiler","oil","lpg","electric boiler","biomass","heat pump","air source","air source heat pump","ground source","radiators","thermostat","smart thermostat","nest","hive","underfloor heating","heating system","hot water cylinder","immersion heater","boiler breakdown","boiler service","annual service","gas safe","home emergency","frozen pipes","no heating","expansion vessel","circulation pump","zone valve"],
  "/insurance/appliance-cover": ["washing machine","washer","washer dryer","tumble dryer","dryer","dishwasher","fridge","freezer","fridge freezer","american fridge","chest freezer","oven","double oven","single oven","cooker","electric cooker","gas cooker","hob","induction hob","gas hob","range cooker","microwave","extractor","cooker hood","tv","television","smart tv","kettle","toaster","vacuum","bosch","miele","samsung","lg","aeg","hotpoint","beko","whirlpool","indesit","neff","siemens","smeg","dyson","hoover","zanussi","candy","bush","logik","hisense","haier","electrolux","rangemaster","stoves","belling","liebherr","fisher paykel","panasonic","sharp","russell hobbs","multi appliance","kitchen bundle"],
  "/insurance/fine-art-and-collections": ["necklace","ring","engagement ring","wedding ring","eternity ring","signet ring","earrings","studs","hoops","bracelet","bangle","pendant","brooch","tiara","cufflinks","chain","locket","anklet","charm bracelet","diamond","sapphire","ruby","emerald","pearl","opal","topaz","aquamarine","amethyst","tanzanite","platinum","white gold","yellow gold","rose gold","gold","silver","solitaire","rolex","omega","cartier","patek","patek philippe","audemars piguet","ap","tag heuer","breitling","tudor","longines","iwc","jaeger lecoultre","jaeger-lecoultre","hublot","panerai","vacheron constantin","richard mille","grand seiko","seiko","tissot","chopard","piaget","zenith","watches","luxury watch","painting","oil painting","watercolour","canvas","print","etching","sculpture","bronze","statue","ceramics","porcelain","pottery","antique","antiques","old master","modern art","contemporary art","gallery","sotheby's","sothebys","christie's","christies","bonhams","auction","fine wine","wine cellar","wine collection","vintage wine","en primeur","whisky","whiskey","scotch","single malt","port","champagne","bordeaux","burgundy","spirits","cognac","stamps","stamp collection","philately","coins","coin collection","numismatics","bullion","memorabilia","sports memorabilia","autographs","first editions","rare books","manuscripts","vinyl records","records","handbags","designer handbag","hermes","birkin","chanel","kelly bag","louis vuitton","gucci","prada","militaria","medals","antique clocks","clocks","longcase clock","grandfather clock","barometers","silverware","antique furniture","tapestry","jade","netsuke","violin","guitar collection","comics","trading cards","lego","model railway","scheduled","heirloom"],
  "/insurance/listed-buildings": ["georgian","victorian","edwardian","tudor","jacobean","regency","queen anne","medieval","elizabethan","palladian","gothic","arts and crafts","grade i","grade 1","grade ii","grade 2","grade ii star","grade 2*","grade a","grade b","manor","manor house","rectory","old rectory","vicarage","hall","farmhouse","oast house","oast","watermill","mill","windmill","gatehouse","lodge","folly","almshouse","coach house","church conversion","chapel","priory","abbey","castle","pele tower","dovecote","tithe barn","granary","mews","townhouse","period property","period home","historic building","historic home","heritage property","conservation area","ancient monument","scheduled monument","period features"],
  "/insurance/thatched-properties": ["thatched cottage","thatched roof","long straw","water reed","combed wheat reed","wheat reed","norfolk reed","devon reed","straw thatch","reed thatch","ridge","re-thatch","rethatch","master thatcher","thatcher","chocolate box","country cottage","rose cottage","spark arrestor","thatch fire"],
  "/insurance/non-standard-construction": ["timber frame","oak frame","green oak","cob","clunch","wattle and daub","daub","flint","flint wall","stone","stone built","granite","slate","single skin","single brick","solid wall","solid brick","no fines","concrete","prc","precast reinforced concrete","precast concrete","steel frame","steel framed","prefab","prefabricated","system build","system built","wimpey no fines","airey","cornish unit","laing easiform","easiform","reema","dorran","mundic","bison","unity","woolaway","colt","hawksley","orlit","tarran","boot","boswell","wates","trusteel","non-traditional","non traditional","designated defective","straw bale","cross laminated timber","clt","sips","modular","modular home","kit home","earth building","rammed earth","asbestos","corrugated iron","icf","shipping container","container home","hempcrete","weatherboard","flat roof","felt roof","metal roof"],
  "/insurance/second-homes": ["holiday let","airbnb","air bnb","short let","short term let","self catering","self-catering","pied a terre","pied-a-terre","bolthole","weekend home","coastal","seaside","beachfront","waterside","log cabin","chalet","ski chalet","villa","apartment abroad","overseas property","spain","france","portugal","italy","greece","cyprus","florida","turkey","static caravan","caravan","park home","beach hut","cabin","summer house","gite","finca","furnished holiday let","fhl","country retreat"],
  "/insurance/unoccupied-property": ["empty property","vacant","vacant property","probate property","bereavement","deceased estate","deceased","inherited","inherited property","executor","estate","between tenants","between owners","awaiting sale","awaiting probate","awaiting renovation","void property","void","derelict","uninhabited","standing empty","in care home","gone into care","long term empty","boarded up","repossessed","chain break","undergoing works"],
  "/insurance/renovation-and-extension": ["rear extension","side extension","loft conversion","garage conversion","basement","basement conversion","cellar conversion","self build","self-build","new build","refurbishment","refurb","doer upper","fixer upper","rewire","replumb","structural","underpinning","knock through","open plan","building works","building work","contract works","jct","single storey","double storey","orangery","conservatory","garden room","annexe","barn conversion","full renovation","strip out","reroof","re-roof","new roof","kitchen extension","planning permission"],
  "/insurance/everyday/home": ["bungalow","terraced","terrace","mid terrace","end terrace","semi detached","semi-detached","semi","detached","maisonette","studio flat","studio","new build","ex council","ex-council","leasehold","freehold","share of freehold","buildings and contents","combined","tenant contents","tenants","renters","tenant","first time buyer","first-time buyer","home mover","brick","cavity wall","cottage","town house","townhouse","chalet bungalow","dormer bungalow","subsidence","flood","personal possessions","legal expenses","family home"],
  "/insurance/everyday/breakdown-and-bicycle": ["roadside assistance","home start","homestart","national recovery","onward travel","european breakdown","euro breakdown","vehicle recovery","rescue","misfuel","misfuelling","flat battery","puncture","road bike","racing bike","mountain bike","mtb","hybrid bike","electric bike","ebike","e-bike","gravel bike","cyclocross","bmx","folding bike","brompton","touring bike","commuter bike","kids bike","specialized","trek","giant","cannondale","canyon","cube","boardman","ribble","bianchi","pinarello","cervelo","scott","merida","whyte","orbea","santa cruz","carrera","voodoo","raleigh","dawes","cyclist","pedal cycle","bike theft","cycle to work","triathlon"],
  "/insurance/business": ["shop","retail","retailer","cafe","coffee shop","restaurant","takeaway","pub","bar","nightclub","salon","hairdresser","barber","barbershop","beauty","beauty salon","nail salon","spa","gym","fitness studio","personal trainer","office","warehouse","storage","ecommerce","e-commerce","online shop","online retailer","market stall","market trader","guest house","guesthouse","b&b","bed and breakfast","serviced accommodation","landlord","buy to let","buy-to-let","btl","rental","rental property","property owner","property owners","hmo","house of multiple occupation","portfolio landlord","student let","commercial property","commercial premises","cyber insurance","fleet","directors and officers","d&o","stock","business interruption","public liability","florist","butcher","bakery","farm shop","garage","car dealer","dealership","childminder","nursery","dog groomer","catering","food truck","event","gallery","antique dealer","jeweller","pharmacy","optician","dentist","vet","charity","not for profit","franchise","manufacturer","wholesaler","distributor"],
  "/insurance/business/trades-and-contractors": ["plumber","electrician","carpenter","joiner","builder","building contractor","general builder","bricklayer","brickie","plasterer","renderer","roofer","painter","decorator","painter and decorator","tiler","gas engineer","heating engineer","boiler engineer","scaffolder","groundworker","groundworks","landscaper","landscape gardener","gardener","tree surgeon","arborist","handyman","handyperson","window cleaner","cleaner","domestic cleaner","end of tenancy","carpet cleaner","oven cleaner","locksmith","flooring","floor fitter","carpet fitter","kitchen fitter","bathroom fitter","drylining","rendering","damp proofing","tanking","pointing","chimney sweep","guttering","gutter cleaner","fencing","fencer","paving","driveway","block paving","tarmac","demolition","asbestos removal","insulation","loft insulation","spray foam","solar panel installer","ev charger installer","cctv installer","alarm installer","aerial installer","sign writer","glazier","window fitter","pest control","public liability","employers liability","tool cover","cis","contract works","plant","tradesman","subcontractor","sole trader"],
  "/insurance/business/professional-indemnity": ["architect","architectural technologist","structural engineer","civil engineer","mechanical engineer","electrical engineer","building services engineer","engineer","surveyor","quantity surveyor","building surveyor","chartered surveyor","valuer","estate agent","letting agent","interior designer","garden designer","graphic designer","web designer","product designer","designer","consultant","management consultant","business consultant","it consultant","software developer","web developer","app developer","programmer","data analyst","accountant","bookkeeper","auditor","tax adviser","financial adviser","ifa","wealth manager","mortgage broker","mortgage adviser","insurance broker","recruitment","recruiter","recruitment agency","marketing agency","marketing consultant","advertising agency","pr agency","copywriter","content writer","social media manager","seo consultant","coach","life coach","business coach","executive coach","therapist","counsellor","psychotherapist","tutor","private tutor","trainer","translator","photographer","videographer","project manager","planning consultant","health and safety consultant","hr consultant","virtual assistant","proofreader","editor","errors and omissions","e&o","professional advice","professional services"],
  "/insurance/private-client": ["high net worth","hnw","high-net-worth","ultra high net worth","uhnw","wealthy","affluent","wealth","country estate","large estate","mansion","stately home","multiple homes","multiple properties","property portfolio","high value home","high value","prime property","prime central london","super prime","family office","private wealth","art collection","classic car collection","car collection","yacht","superyacht","private jet","jewellery collection","watch collection","kidnap and ransom","household staff","domestic staff","nanny","housekeeper","landed estate","valuables","chattels","bespoke","concierge","net worth"],
};

export const ALL_COVERS: CoverIndexEntry[] = BASE_COVERS.map((c) => ({
  ...c,
  tags: [...new Set([...c.tags, ...(EXTRA[c.href] ?? [])])],
}));
